services:
  - type: web
    name: bib-recognition
    runtime: docker
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: bib-recognition-db
          property: connectionString
      - key: COOKIE_SECURE
        value: "true"
      - key: MAX_UPLOAD_SIZE_MB
        value: "20"
      - key: SECRET_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false

databases:
  - name: bib-recognition-db
    databaseName: bib_recognition
    plan: free
